spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.129.207.185:3306/test
    username: root
    password: zhanjob
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user
logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BaseBinder: TRACE
    org.hibernate.type.descriptor.sql.BASEEXTRACTOR: TRACE
    com.itmuch: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:zhao@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}