eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:zhao@localhost:8761/eureka/
spring:
  application:
    name: gateway
server:
  port: 8020
zuul:
  routes:
    user:
      path: /u/**
      service-id: user

#  ignored-services: movie-ribbon-with-hystrix

ribbon:
  eureka:
    enabled: false

user:   # service-id
  ribbon:
    listOfServers: http://localhost:8091/,http://localhost:8094/