spring:
  application:
    name: movie-ribbon-customizing

server:
  port: 8072

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:zhao@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule