security:
  basic:
    enabled: true
  user:
    name: admin
    password: zhao
server:
  port: 8761
eureka:
  datacenter: cloud
  environment: prod_zhao
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:zhao@${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
#  server:
#    enable-self-preservation: false