spring:
  application:
    name: movie-ribbon-without-eureka

server:
  port: 8073

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:zhao@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
   enabled: false
user:
  ribbon:
    listOfServers: localhost:8091